# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Masonry'
#pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'DZNEmptyDataSet'
pod "MBProgressHUD", '~> 1.0.0'
pod 'JXPagingView/Pager'
pod 'JXCategoryView', '= 1.5.6'


  # Pods for YJ

  target 'YJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJUITests' do
    # Pods for testing
  end

end
