# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Masonry'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'DZNEmptyDataSet'
pod "MBProgressHUD", '~> 1.0.0'
pod 'JXPagingView/Pager'
pod 'JXCategoryView', '= 1.5.6'
pod 'JXPagingView/Pager'
pod 'JXCategoryView', '= 1.5.6'
pod 'JCore'
pod 'JPush'
pod 'MMKV', '= 1.1.2'
pod "JSONModel", '~> 1.7.0'
pod 'TZImagePickerController', '= 3.4.2' #iOS8 and later
pod 'MNFloatBtn'

  # Pods for YJ

  target 'YJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJUITests' do
    # Pods for testing
  end

end
